version: "3.7"
services:
  order-receiver:
    image: kennethreitz/httpbin
    container_name: order-receiver
    restart: always
    ports:
      - 3001:80
    networks:
      - backend_services
networks:
  backend_services:
    driver: bridge